/**
 * NSSF NS Selection
 * NSSF Network Slice Selection Service. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "NetworkSliceInformationDocumentApi.h"

#include "Helpers.h"
#include "nssf_config.hpp"
#include "sbi_helper.hpp"

extern std::unique_ptr<oai::config::nssf::nssf_config> nssf_cfg;

namespace oai {
namespace nssf_server {
namespace api {

using namespace oai::_3gpp::model::helpers;
using namespace oai::_3gpp::model;
using namespace oai::common::sbi;

const std::string NetworkSliceInformationDocumentApi::base =
    sbi_helper::NssfNsSelectionBase;

NetworkSliceInformationDocumentApi::NetworkSliceInformationDocumentApi(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : router(rtr) {}

void NetworkSliceInformationDocumentApi::init() {
  setupRoutes();
}

void NetworkSliceInformationDocumentApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Get(
      *router,
      base + nssf_cfg->local().get_sbi().get_api_version() +
          sbi_helper::NssfNsSelectionPathNetworSliceInformation,
      Routes::bind(
          &NetworkSliceInformationDocumentApi::n_s_selection_get_handler,
          this));

  // Default handler, called when a route is not found
  router->addCustomHandler(Routes::bind(
      &NetworkSliceInformationDocumentApi::
          network_slice_information_document_api_default_handler,
      this));
}

std::pair<Pistache::Http::Code, std::string>
NetworkSliceInformationDocumentApi::handleParsingException(
    const std::exception& ex) const noexcept {
  try {
    throw;
  } catch (nlohmann::detail::exception& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
    // } catch (oai::nssf_server::helpers::ValidationException &e) {
    //     return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (std::exception& e) {
    return std::make_pair(
        Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

std::pair<Pistache::Http::Code, std::string>
NetworkSliceInformationDocumentApi::handleOperationException(
    const std::exception& ex) const noexcept {
  return std::make_pair(Pistache::Http::Code::Internal_Server_Error, ex.what());
}

void NetworkSliceInformationDocumentApi::n_s_selection_get_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the query params
    auto nfTypeQuery = request.query().get("nf-type");
    std::optional<NFType> nfType;
    if (nfTypeQuery.has_value()) {
      NFType valueQuery_instance;
      if (fromStringValue(nfTypeQuery.value(), valueQuery_instance)) {
        nfType = valueQuery_instance;
      }
    }
    auto nfIdQuery = request.query().get("nf-id");
    std::optional<std::string> nfId;
    if (nfIdQuery.has_value()) {
      std::string valueQuery_instance;
      if (fromStringValue(nfIdQuery.value(), valueQuery_instance)) {
        nfId = valueQuery_instance;
      }
    }
    auto sliceInfoRequestForRegistrationQuery = request.query().get(
        sbi_helper::NssfNsSelectionParametersSliceInfoRequestForRegistration);
    std::optional<SliceInfoForRegistration> sliceInfoRequestForRegistration;
    if (sliceInfoRequestForRegistrationQuery.has_value()) {
      SliceInfoForRegistration valueQuery_instance;
      if (fromStringValueHelper(
              sliceInfoRequestForRegistrationQuery.value(),
              valueQuery_instance)) {
        sliceInfoRequestForRegistration = valueQuery_instance;
      }
    }
    auto sliceInfoRequestForPduSessionQuery =
        request.query().get("slice-info-request-for-pdu-session");
    std::optional<SliceInfoForPDUSession> sliceInfoRequestForPduSession;
    if (sliceInfoRequestForPduSessionQuery.has_value()) {
      SliceInfoForPDUSession valueQuery_instance;
      if (fromStringValueHelper(
              sliceInfoRequestForPduSessionQuery.value(),
              valueQuery_instance)) {
        sliceInfoRequestForPduSession = valueQuery_instance;
      }
    }
    auto sliceInfoRequestForUeCuQuery =
        request.query().get("slice-info-request-for-ue-cu");
    std::optional<SliceInfoForUEConfigurationUpdate> sliceInfoRequestForUeCu;
    if (sliceInfoRequestForUeCuQuery.has_value()) {
      SliceInfoForUEConfigurationUpdate valueQuery_instance;
      if (fromStringValueHelper(
              sliceInfoRequestForUeCuQuery.value(), valueQuery_instance)) {
        sliceInfoRequestForUeCu = valueQuery_instance;
      }
      Logger::nssf_app().error("NS Selection failure !!!");
      response.send(
          Pistache::Http::Code::Not_Found,
          "The requested method does not exist");
      return;
    }
    auto homePlmnIdQuery = request.query().get("home-plmn-id");
    std::optional<PlmnId> homePlmnId;
    if (homePlmnIdQuery.has_value()) {
      PlmnId valueQuery_instance;
      if (fromStringValue(homePlmnIdQuery.value(), valueQuery_instance)) {
        homePlmnId = valueQuery_instance;
      }
    }
    auto taiQuery = request.query().get("tai");
    std::optional<Tai> tai;
    if (taiQuery.has_value()) {
      Tai valueQuery_instance;
      if (fromStringValue(taiQuery.value(), valueQuery_instance)) {
        tai = valueQuery_instance;
      }
    }
    auto supportedFeaturesQuery = request.query().get("supported-features");
    std::optional<std::string> supportedFeatures;
    if (supportedFeaturesQuery.has_value()) {
      std::string valueQuery_instance;
      if (fromStringValue(
              supportedFeaturesQuery.value(), valueQuery_instance)) {
        supportedFeatures = valueQuery_instance;
      }
    }

    try {
      this->n_s_selection_get(
          nfType, nfId, sliceInfoRequestForRegistration,
          sliceInfoRequestForPduSession, sliceInfoRequestForUeCu, homePlmnId,
          tai, supportedFeatures, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

void NetworkSliceInformationDocumentApi::
    network_slice_information_document_api_default_handler(
        const Pistache::Rest::Request&,
        Pistache::Http::ResponseWriter response) {
  response.send(
      Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

bool fromStringValueHelper(
    const std::string& inStr,
    oai::_3gpp::model::SliceInfoForRegistration& value) {
  Logger::nssf_sbi().info(
      " Query_PARAM::SLICE_INFO_RESGISTRATION - %s", inStr.c_str());
  nlohmann::json::parse(inStr.c_str()).get_to(value);
  return true;
}

bool fromStringValueHelper(
    const std::string& inStr,
    oai::_3gpp::model::SliceInfoForPDUSession& value) {
  Logger::nssf_sbi().info(
      " Query_PARAM slice-info-request-for-pdu-session - %s", inStr.c_str());
  nlohmann::json::parse(inStr.c_str()).get_to(value);
  return true;
}

bool fromStringValueHelper(
    const std::string& inStr,
    oai::_3gpp::model::SliceInfoForUEConfigurationUpdate& value) {
  Logger::nssf_sbi().info(
      " Query_PARAM slice-info-request-for-registration - %s", inStr.c_str());
  nlohmann::json::parse(inStr.c_str()).get_to(value);
  return true;
}

}  // namespace api
}  // namespace nssf_server
}  // namespace oai
