#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface NSSF service
#   Valid for Rocky Linux 8.7+
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM docker.io/rockylinux:8 AS oai-nssf-builder

ENV IS_DOCKERFILE=1

RUN dnf install 'dnf-command(config-manager)' -y && \
    dnf config-manager --set-enabled powertools && \
    dnf install epel-release -y && crb enable && \
    dnf update -y && \
    # here just to display the current version
    cat /etc/os-release && \
    dnf install -y \
        psmisc \
        git \
        diffutils \
        libasan \
        wget \
        file && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
    echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

# Some GIT configuration command quite useful
RUN git config --global https.postBuffer 123289600 && \
    git config --global http.sslverify false

# Copying source code
WORKDIR /openair-nssf
COPY . /openair-nssf

# Installing and Building NSSF
WORKDIR /openair-nssf/build/scripts
RUN ./build_nssf --install-deps --force && \
    ldconfig
RUN ./build_nssf --clean --Verbose --build-type Release --jobs && \
    ldd /openair-nssf/build/nssf/build/nssf && \
    mv /openair-nssf/build/nssf/build/nssf /openair-nssf/build/nssf/build/oai_nssf && \
    sed -i -e "s@nf-root-folder@nssf@" -e "s@nf-config-file@nssf.conf@" \
      ../common-build/docker-scripts/entrypoint.py

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM docker.io/rockylinux:8-minimal as oai-nssf
ENV TZ=Europe/Paris

# We install some debug tools for the moment in addition of mandatory libraries
RUN microdnf update -y && \
    microdnf install -y \
      python3 \
      python3-pip \
      tzdata \
#      libasan \
      procps-ng \
      psmisc \
      net-tools \
      libicu \
      boost \
      libevent \
      findutils \
      libconfig && \
    pip3 install jinja2 && \
    microdnf clean all -y && \
    rm -rf /var/cache/yum /var/cache/dnf

# Copying executable and generated libraries
WORKDIR /openair-nssf/bin
COPY --from=oai-nssf-builder \
    /openair-nssf/build/nssf/build/oai_nssf \
    /openair-nssf/build/common-build/docker-scripts/entrypoint.py \
    /openair-nssf/scripts/healthcheck.sh \
    ./

COPY --from=oai-nssf-builder \
# Copying only the packages built from source
    /usr/local/lib64/libpistache.so.0 \
    /usr/local/lib/libnghttp2_asio.so \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /usr/local/lib64/libspdlog.so \
    /usr/local/lib64/libfmt.so \
# libyaml-cpp is installed via epel-8
# and epel-8 cannot be installed on ubi-minimal
    /lib64/libyaml-cpp.so.0.6 \
    /usr/lib64/

RUN ldconfig && \
    ldd /openair-nssf/bin/oai_nssf

# Copying template configuration files
# The configuration folder will be flat
WORKDIR /openair-nssf/etc
COPY --from=oai-nssf-builder \
    /openair-nssf/etc/nssf.conf \
    /openair-nssf/etc/nssf_slice_config.yaml \
    ./

WORKDIR /openair-nssf

# expose ports
EXPOSE 80/tcp 8080/tcp
# healthcheck
HEALTHCHECK --interval=10s \
            --timeout=15s \
            --retries=6 \
    CMD /openair-nssf/bin/healthcheck.sh

ENTRYPOINT ["python3", "/openair-nssf/bin/entrypoint.py"]
CMD ["/openair-nssf/bin/oai_nssf", "-c", "/openair-nssf/etc/nssf.conf", "-o"]
