#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface NSSF service
#   Valid for Ubuntu-18.04 (bionic)
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM oai-nssf-base:latest as oai-nssf-builder

WORKDIR /openair-nssf/
COPY . /openair-nssf
RUN cp -Rf /openair-nssf-ext-ref /openair-nssf/build/ext

# Building NSSF
WORKDIR /openair-nssf/build/scripts
RUN ./build_nssf --clean --Verbose --build-type Release --jobs

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM ubuntu:bionic as oai-nssf
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
# We install some debug tools for the moment in addition of mandatory libraries
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
      psmisc \
      net-tools \
      tzdata \
      bc \
      tshark \
      perl \
      libasan4 \
      libnghttp2-14 \
      libhogweed4 \
      libconfig++9v5 \
      libcurl4-gnutls-dev \
  && rm -rf /var/lib/apt/lists/*

# Copying executable and generated libraries
WORKDIR /openair-nssf/bin
COPY --from=oai-nssf-builder /openair-nssf/build/nssf/build/nssf oai_nssf
COPY --from=oai-nssf-builder /openair-nssf/scripts/entrypoint.sh .

COPY --from=oai-nssf-builder /usr/local/lib/libpistache.so /usr/local/lib/
COPY --from=oai-nssf-builder /usr/lib/x86_64-linux-gnu/libnettle.so.6 /usr/local/lib/
COPY --from=oai-nssf-builder /usr/lib/libboost_system.so.1.67.0 /usr/local/lib/
COPY --from=oai-nssf-builder /usr/local/lib/libnghttp2_asio.so.1 /usr/local/lib/

RUN ldconfig

WORKDIR /openair-nssf/etc
COPY --from=oai-nssf-builder /openair-nssf/etc/nssf.conf .
COPY --from=oai-nssf-builder /openair-nssf/etc/nssf_slice_config.json .

WORKDIR /openair-nssf

EXPOSE 80/tcp

ENTRYPOINT ["/bin/bash","/openair-nssf/bin/entrypoint.sh"]
CMD ["/openair-nssf/bin/oai_nssf", "-c" , "/openair-nssf/etc/nssf.conf", "-o"]
