/**
* NSSF NS Selection
* NSSF Network Slice Selection Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "NetworkSliceInformationDocumentApiImpl.h"
#include "Helpers.h"

namespace oai                  {
namespace nssf_server {
namespace api                  {

using namespace oai::nssf_server::helpers;
using namespace oai::nssf_server::model;

NetworkSliceInformationDocumentApiImpl::NetworkSliceInformationDocumentApiImpl(
        std::shared_ptr<Pistache::Rest::Router> rtr, nssf_app* nssf_app_inst,
    std::string address)
    : NetworkSliceInformationDocumentApi(rtr),
      m_nssf_app(nssf_app_inst),
      m_address(address) {}

void NetworkSliceInformationDocumentApiImpl::n_s_selection_get(const Pistache::Optional<NFType> &nfType, const Pistache::Optional<std::string> &nfId, const Pistache::Optional<SliceInfoForRegistration> &sliceInfoRequestForRegistration, const Pistache::Optional<SliceInfoForPDUSession> &sliceInfoRequestForPduSession, const Pistache::Optional<SliceInfoForUEConfigurationUpdate> &sliceInfoRequestForUeCu, const Pistache::Optional<PlmnId> &homePlmnId, const Pistache::Optional<Tai> &tai, const Pistache::Optional<std::string> &supportedFeatures, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}  // namespace api
}  // namespace nssf
}  // namespace oai

