/**
 * NSSF NS Selection
 * NSSF Network Slice Selection Service. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * NetworkSliceInformationDocumentApiImpl.h
 *
 *
 */

#ifndef NETWORK_SLICE_INFORMATION_DOCUMENT_API_IMPL_H_
#define NETWORK_SLICE_INFORMATION_DOCUMENT_API_IMPL_H_

#include <memory>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <NetworkSliceInformationDocumentApi.h>

#include <optional>

#include "AuthorizedNetworkSliceInfo.h"
#include "NFType.h"
#include "PlmnId.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include "SliceInfoForPDUSession.h"
#include "SliceInfoForRegistration.h"
#include "SliceInfoForUEConfigurationUpdate.h"
#include "nssf_app.hpp"

#include "Tai.h"
#include <string>

namespace oai {
namespace nssf_server {
namespace api {

class NetworkSliceInformationDocumentApiImpl
    : public oai::nssf_server::api::NetworkSliceInformationDocumentApi {
 public:
  NetworkSliceInformationDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, nssf::nssf_app* nssf_app_inst,
      std::string address);
  ~NetworkSliceInformationDocumentApiImpl() {}

  void n_s_selection_get(
      const std::optional<oai::_3gpp::model::NFType>& nfType,
      const std::optional<std::string>& nfId,
      const std::optional<oai::_3gpp::model::SliceInfoForRegistration>&
          sliceInfoRequestForRegistration,
      const std::optional<oai::_3gpp::model::SliceInfoForPDUSession>&
          sliceInfoRequestForPduSession,
      const std::optional<oai::_3gpp::model::SliceInfoForUEConfigurationUpdate>&
          sliceInfoRequestForUeCu,
      const std::optional<oai::_3gpp::model::PlmnId>& homePlmnId,
      const std::optional<oai::_3gpp::model::Tai>& tai,
      const std::optional<std::string>& supportedFeatures,
      Pistache::Http::ResponseWriter& response);

 private:
  nssf::nssf_app* m_nssf_app;
  std::string m_address;
};

}  // namespace api
}  // namespace nssf_server
}  // namespace oai

#endif
